---
kind: Service
apiVersion: v1
metadata:
  name: spa-practice-loadbalancer
spec:
  selector:
    app: spa-practice-pod
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 80
      # Port to forward to inside the pod
      targetPort: 8080
      # Port accessible outside cluster
      nodePort: 30001
  type: LoadBalancer

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spa-pratice-pod
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: spa-practice-pod
    spec:
      containers:
        - name: spa-practice
          image: ziveso/spa-practice
          ports:
            - containerPort: 8080
